### ISSUE TITLE
render_to_string - Django 1.8 changed how templates operate

### ISSUE THREAD

**Issue by philippeowagner** [arteria/django-compat#38]
* http://django.readthedocs.org/en/latest/topics/templates.html#django.template.loader.render_to_string
* based on https://github.com/mysociety/mapit/blob/master/mapit/djangopatch.py#L4-L12

        """ Django 1.8 changed how templates operate. """
        import django
        if django.get_version() >= '1.8':
            from django.template.loader import render_to_string
        else:
            from django.template import loader, RequestContext

            def render_to_string(template_name, context=None, request=None):
                context_instance = RequestContext(request) if request else None
                return loader.render_to_string(template_name, context, context_instance

**Comment by bashu** [comment]
+1

**Comment by ad-m** [comment]
+1

**Comment by KeonHee** [comment]
dfdf

1. dfdfd
dfdf
