### ISSUE TITLE
"File" errors in setup.py

### ISSUE THREAD

**Issue by philippeowagner** [arteria/django-compat#46]
@jvamvas please check the forks of @SebCorbin and @kakky0312 - there seems to be an issue in setup.py 

![screen shot 2016-04-25 at 12 41 27](https://cloud.githubusercontent.com/assets/113043/14781529/4f2183c2-0ae3-11e6-8917-22166e9af327.png)

**Comment by jvamvas** [comment]
I think this has already been fixed.
