### ISSUE TITLE
Stop use django-nose as it doesn't support Django<1.8

### ISSUE THREAD

**Issue by ZuluPro** [arteria/django-compat#50]
I think use django-nose is a bad idea because it doesn't support Django<1.8.
So we cannot test this version with the `./runtests.py`.

We should use Django test runner like made here: https://github.com/django-dbbackup/django-dbbackup/blob/master/runtests.py
It also allow to launch any commands like `manage.py`.

**Comment by jvamvas** [comment]
Thank you @ZuluPro, this is a good suggestion.

In the meantime you could use `django-nose==1.4.3`, which is the last version supporting Django 1.4 and 1.7.

**Comment by ZuluPro** [comment]
I would to be able to tests all Django version.
Do you accept a PR if I rewrite the test launcher without nose, it will look like [DBBackup's one](https://github.com/django-dbbackup/django-dbbackup/blob/master/runtests.py) ?

**Comment by jvamvas** [comment]
@ZuluPro That would be great! 😄
