### ISSUE TITLE
WIP django monkey-patcher

### ISSUE THREAD

**Issue by pakal** [arteria/django-compat#51]
Hello,

i'm planning a sprint at pyconfr to build a django compatibility module, which wouldn't behave like an intermediate module (like six for py3k, or like django-compat for django), but directly monkey-patch django with log-lifespan shims.

Thus, django webmaster who want to upgrade wouldn't have to fork/monkeypatch all their broken dependencies, and minor django upgrades would REALLY be minor (i.e would NOT rename/remove methods and attributes used by tons of unmaintained libs).

Would you be OK with integrating this monkey-patching utility to django-compat, to have an all-in-one solution, for BOTH library maintainers and library users ?

**Comment by jvamvas** [comment]
Hello @pakal, it's certainly going to be interesting to see how your idea plays out. Good luck! :)

**Comment by pakal** [comment]
Well DCP is kinda production-ready nows (though it needs more real-life uses), I used it successfully on a big site. 

I linked to django-compat from its repository, for people who need a six-like compatibility layer for a reusable app, and not a project-wide compatibility enforcer. 

I don't know if merging both projects would be worth since they somehow target different people (reusable app developers VS project maintainers), but feel free to link to DCP from your own doc  B-)

https://github.com/pakal/django-compat-patcher

Any opinion about it ?
