### ISSUE TITLE
GitHub project blurb doesn't mention Django 1.10

### ISSUE THREAD

**Issue by Flimm** [arteria/django-compat#52]
This GitHub project doesn't mention Django 1.10 in the blurb:

![Screenshot](https://cloud.githubusercontent.com/assets/355454/19308072/b898b862-9075-11e6-887b-76a8c9aef016.png)

It needs to match the README file.

This also affects the blurb in https://djangopackages.org/packages/p/django-compat/

**Comment by jvamvas** [comment]
Thank you for pointing this out, @Flimm ! :)
