### ISSUE TITLE
Support for Django 1.11 LTS

### ISSUE THREAD

**Issue by philippeowagner** [arteria/django-compat#53]
Django 1.11 LTS will be the last Django version to support Python 2. The next major release, Django 2.0, will only support Python 3.5+. So Django 1.11.x will probably be the last supported version for LTS-to-LTS support of django-compat (1.8-1.11). See Django's [release notes](https://docs.djangoproject.com/en/1.11/releases/1.11/#python-compatibility) for more.

**Comment by walterrenner** [comment]
There are Errors when running the test against Django 1.11:

```
======================================================================
FAIL: test_get_template_loaders (compat.tests.test_compat.CompatTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/walterrenner/workspace/django-compat/compat/tests/test_compat.py", line 247, in test_get_template_loaders
    self.assertEqual(len(template_loaders), 2)
AssertionError: 1 != 2
```

I will take a look in the next days.
