### ISSUE TITLE
get_user_model doesn't quite work as intended

### ISSUE THREAD

**Issue by mathiasose** [arteria/django-compat#9]
I'm getting the same issue as https://github.com/arteria/django-hijack/issues/38. django-compat is returning a string argument where the get_object_or_404 function needs a model argument

The problem is over at https://github.com/arteria/django-compat/blob/master/compat/__init__.py#L162. Switching the try blocks  so that `django.contrib.auth.get_user_model` is the first choice would solve my problem on 1.7. Don't know if it would break something on other versions though.

**Comment by yannik-ammann** [comment]
thanks for the hin!
django-compat 1.0.1 is released on pypi
